apiVersion: apps/v1
kind: Deployment
metadata:
  name: "cloudify-hello-world-2-app"
  labels:
    app: cloudify-hello-world-2
    manager: cloudify
    tier: app
spec:
  selector:
    matchLabels:
      app: cloudify-hello-world-2
      manager: cloudify
      tier: app
  replicas: 3
  template:
    metadata:
      labels:
        app: cloudify-hello-world-2
        manager: cloudify
        tier: app
    spec:
      containers:
      - name: cloudify-hello-world-2
        image: gcr.io/google-samples/node-hello:1.0
        ports:
        - containerPort: 8080
          name: http-server
        resources:
          limits:
            cpu: 1
            memory: 128Mi
          requests:
            cpu: 0.5
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: "cloudify-hello-world-2-svc"
  labels:
    app: cloudify-hello-world-2
    manager: cloudify
    tier: app
spec:
  selector:
    app: cloudify-hello-world-2
    manager: cloudify
    tier: app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
