# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [published]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      ## Runs a set of commands using the runners shell
      - name: Download Cloudify CLI
        id: download_cli
        run: curl -O https://repository.cloudifysource.org/cloudify/latest/5.0.5/ga-release/cloudify-cli_5.0.5.1~ga_amd64.deb
        
      - name: Install Cloudify CLI
        id: install_cli
        run: sudo dpkg -i cloudify-cli_5.0.5.1~ga_amd64.deb
      
      - name: Setup Cloudify
        id: set_up_cloudify
        run: |
          sudo cfy profiles use 54.176.36.209 -u admin -p admin -t default_tenant
          sudo cfy blueprints upload https://github.com/moshemizrachi/k8s/raw/master/K8s_BP.zip -n blueprint_v2.yaml -b "k8_v2"
          sudo cfy deployments update -b k8_v2 K8s_deployment
          
          
      
      
          

        
